### ISSUE TITLE
环境变量大小超限怎么增加限额？

### ISSUE THREAD

**Issue by applusuck** [lukesyy/jd_yun#12]
![image](https://user-images.githubusercontent.com/86282095/125030072-1cb50c00-e0bd-11eb-9576-6fcd8be442b6.png)
secret里面添加的变量有点多，有办法增加限额吗？求大佬帮忙

**Comment by greenwave1987** [comment]
把cookie精简一下，只要pt_key=.................................................................; pt_pin=......................; 其他删掉。

**Comment by dnete** [comment]
李金岗
13884845155
9emGQfyFT1Z2cSb
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
