### ISSUE TITLE
大佬，财富岛的cookie失效会不停发消息

### ISSUE THREAD

**Issue by AndrewAndrea** [lukesyy/jd_yun#13]
这个在哪里改，我自己改一下，cookie失效了，重新更新部署后，发现以前的还在运行。还会不停发送消息。感谢大佬

**Comment by AndrewAndrea** [comment]
就是惊喜财富岛挂机的

**Comment by AndrewAndrea** [comment]
有毒，删除了云函数竟然还会发，。。。

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
4KkzMDbF0w5iGWr
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
