### ISSUE TITLE
要不要清理一下失效的脚本

### ISSUE THREAD

**Issue by tonghuanming** [lukesyy/jd_yun#14]
crazyjoy的三个脚本已经失效了 还有其他一些

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
MlxzcRQWKyY8TdU
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
