### ISSUE TITLE
收藏夹和收藏的店铺能不能设置不清空？

### ISSUE THREAD

**Issue by wcwangjianjie** [lukesyy/jd_yun#15]
收藏夹和收藏的店铺能不能设置不清空？

**Comment by zwb124** [comment]
会清空收藏夹的吗？

**Comment by zwb124** [comment]
设置一下变量就不会把你自己的清空了

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
E1Sny0kjTmsGgcC
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
