### ISSUE TITLE
大佬，我这这样怎么弄啊

### ISSUE THREAD

**Issue by clq12** [lukesyy/jd_yun#16]
最后action的时候卡在这了
![QQ截图20210811221418](https://user-images.githubusercontent.com/45648440/129045259-91457234-4b01-4e3f-b67c-fec917d5b60d.png)

Run repo-sync/github-sync@v2
/usr/bin/docker run --name ghcrioreposyncgithubsyncv230_b719ca --label 48c8ce --workdir /github/workspace --rm -e PAT -e dst_key -e INPUT_SOURCE_REPO -e INPUT_SOURCE_BRANCH -e INPUT_DESTINATION_BRANCH -e INPUT_GITHUB_TOKEN -e INPUT_SYNC_TAGS -e GITHUB_TOKEN -e SYNC_TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jd/jd":"/github/workspace" ghcr.io/repo-sync/github-sync:v2.3.0  "https://github.com/lukesyy/jd_yun.git" "main:main"

**Comment by clq12** [comment]
> 一样，应该是正常的

你这样子之后还可以继续进行后面的步骤吗？

**Comment by pan176** [comment]
可以，不用管它
