### ISSUE TITLE
强烈建议不清空收藏夹

### ISSUE THREAD

**Issue by zwb124** [lukesyy/jd_yun#18]
一下收藏的东西都没了这太不方便了，我可以定期自己清空的，我要修改什么才能不自动清空收藏夹和关注店铺呢

**Comment by zwb124** [comment]
找到设置的参数了，不过还是很麻烦，如果我直接把取关的任务停止是不是就不再自动取关了

**Comment by lukesyy** [comment]
是的 不清空的话会爆满的

**Comment by zwb124** [comment]
> 是的 不清空的话会爆满的

我最后还是按照参数设置了，凑合用吧，不过这系统是真的爽，一天700多京豆，太吓人了，哈哈

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
EmHT8iRoXSBs4wK
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
