### ISSUE TITLE
部署上了，测试出这个结果，我是哪个步骤做漏了吗？

### ISSUE THREAD

**Issue by sakuragundams** [lukesyy/jd_yun#19]
START RequestId:f400fa2d-4487-4561-aa0c-177f8b4c80c5

2021-08-17T03:49:17.272Z f400fa2d-4487-4561-aa0c-177f8b4c80c5 没参数你在这测啥呢?!你是用Timer触发器触发的吗!脑瓜子给你打掉!

Response RequestId:f400fa2d-4487-4561-aa0c-177f8b4c80c5 RetMsg:null

END RequestId:f400fa2d-4487-4561-aa0c-177f8b4c80c5

Report RequestId:f400fa2d-4487-4561-aa0c-177f8b4c80c5 Duration:2ms Memory:64MB MemUsage:7.312500MB

**Comment by sakuragundams** [comment]
原来是腾讯云新版编辑器没有地方修改timer测试模板

**Comment by imdalao** [comment]
在右下角切换旧版编辑器
