### ISSUE TITLE
京东全民开红包获得红包好像有BUG 会递归字符串 请求助力接口

### ISSUE THREAD

**Issue by ziyingjie** [lukesyy/jd_yun#2]
04 0|elecV2P  | [jd_z_h...js info][2021-06-16 21:31:04.269] 早起打卡(06:00-09:00)
21:31:04 0|elecV2P  | [jd_z_h...js info][2021-06-16 21:31:04.270] └ 这类型任务没有抓到包，过两天更新
21:31:05 0|elecV2P  | [jd_z_h...js info][2021-06-16 21:31:05.279] 一分钱造爆款电器
21:31:05 0|elecV2P  | [jd_z_h...js info][2021-06-16 21:31:05.369] └ 任务领取成功
21:31:05 0|elecV2P  | [jd_sta...js info][2021-06-16 21:31:05.490] 浏览：3
21:31:07 0|elecV2P  | [jd_sta...js info][2021-06-16 21:31:07.581] 浏览：22
21:31:07 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:07.794] 开始领取【关注4个精选频道】任务所得红包奖励
21:31:07 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:07.976] 红包领取成功，获得0.02元
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.196] 发起助力红包 成功：红包ID 311839292
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.307] 京东全民开红包获得红包：0.12元
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.308] 有剩余助力机会则给作者lxk0301进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.309] 账号 1 test 开始给作者lxk0301 { 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.417] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.418] 账号 1 test 开始给作者lxk0301 " 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.521] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.521] 账号 1 test 开始给作者lxk0301 u 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.617] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.617] 账号 1 test 开始给作者lxk0301 r 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.717] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.717] 账号 1 test 开始给作者lxk0301 l 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.807] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.807] 账号 1 test 开始给作者lxk0301 " 进行助力
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.907] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:08 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:08.907] 账号 1 test 开始给作者lxk0301 : 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.014] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.014] 账号 1 test 开始给作者lxk0301 " 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.139] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.139] 账号 1 test 开始给作者lxk0301 h 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.236] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.237] 账号 1 test 开始给作者lxk0301 t 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.330] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.330] 账号 1 test 开始给作者lxk0301 t 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.427] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.427] 账号 1 test 开始给作者lxk0301 p 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.527] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.527] 账号 1 test 开始给作者lxk0301 s 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.627] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.627] 账号 1 test 开始给作者lxk0301 : 进行助力
21:31:09 0|elecV2P  | [jd_jxmc.js  info][2021-06-16 21:31:09.646] 完成任务：浏览签到领红包5秒,浏览工厂5秒,浏览农场5秒,浏览财富岛5秒,浏览官方群5秒,浏览银行福利5秒
21:31:09 0|elecV2P  | [jd_sta...js info][2021-06-16 21:31:09.676] 任务：明星应援关注店铺，已完成
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.717] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.717] 账号 1 test 开始给作者lxk0301 / 进行助力
21:31:09 0|elecV2P  | [jd_jxmc.js  info][2021-06-16 21:31:09.787] 去做任务：浏览签到领红包5秒,浏览工厂5秒,浏览农场5秒,浏览财富岛5秒,浏览官方群5秒,浏览银行福利5秒
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.816] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.816] 账号 1 test 开始给作者lxk0301 / 进行助力
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.907] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:09 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:09.907] 账号 1 test 开始给作者lxk0301 g 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.011] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.011] 账号 1 test 开始给作者lxk0301 h 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.109] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.109] 账号 1 test 开始给作者lxk0301 p 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.207] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.207] 账号 1 test 开始给作者lxk0301 r 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.307] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.307] 账号 1 test 开始给作者lxk0301 o 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.397] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.397] 账号 1 test 开始给作者lxk0301 x 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.576] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.577] 账号 1 test 开始给作者lxk0301 y 进行助力
21:31:10 0|elecV2P  | [jd_sta...js info][2021-06-16 21:31:10.677] 开始第20个明星小店，ID：2SFR44,明星：白茶
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.678] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.679] 账号 1 test 开始给作者lxk0301 . 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.784] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.784] 账号 1 test 开始给作者lxk0301 c 进行助力
21:31:10 0|elecV2P  | [jd_sta...js info][2021-06-16 21:31:10.787] 白茶给你送好礼啦，快来完成任务抽取专属好礼吧~
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.877] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.877] 账号 1 test 开始给作者lxk0301 o 进行助力
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.977] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:10 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:10.977] 账号 1 test 开始给作者lxk0301 m 进行助力
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.079] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.079] 账号 1 test 开始给作者lxk0301 / 进行助力
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.169] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.170] 账号 1 test 开始给作者lxk0301 h 进行助力
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.267] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.267] 账号 1 test 开始给作者lxk0301 t 进行助力
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.365] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.366] 账号 1 test 开始给作者lxk0301 t 进行助力
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.457] 助力异常：{"code":0,"data":{"biz_code":1,"code":1,"success":false},"rtn_code":0}
21:31:11 0|elecV2P  | [jd_red...js info][2021-06-16 21:31:11.458] 账号 1 test 开始给作者lxk0301 p 进行助力

**Comment by lukesyy** [comment]
这个我已经全部删了
