### ISSUE TITLE
求 云函数部署方法，新教程的部署方法已经更新 对不上

### ISSUE THREAD

**Issue by jopedu** [lukesyy/jd_yun#26]
如题求 云函数部署方法，新教程的部署方法已经更新 对不上

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
gJFjYbBr0mQnuop
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
