### ISSUE TITLE
取关变量突然不起作用了

### ISSUE THREAD

**Issue by zwb124** [lukesyy/jd_yun#31]
不管怎么设置都会清空关注的店铺和商品

**Comment by lukesyy** [comment]
这个没办法 即使不清空每天也会加很多

**Comment by zwb124** [comment]
不是，我的意思是我设定的取关关键字，没用了，每次都把我自己收藏的东西也给清空了，原来没这个问题的，都是晴空到我设定的商品

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
u8swAgalUPY67zm
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
