### ISSUE TITLE
jd_ljd.js脚本失效，运行无报错，但没有领到任何京豆

### ISSUE THREAD

**Issue by karma-sun** [lukesyy/jd_yun#33]
jd_ljd.js脚本失效，运行无报错，但没有领到任何京豆

脚本输出：
当前等级:0 下一级可领取:66京豆
已经过时了~
做任务

做任务:双签领豆;等待完成
{"code":"0","data":{"bizCode":"0","score":"2","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
做任务:种豆得豆;等待完成
{"code":"0","data":{"bizCode":"0","score":"2","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
做任务:京东大药房;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
做任务:正品好药;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":1,"times":1,"maxTimes":4,"growthResult":{"addedGrowth":0}}}
做任务:惊喜福利;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"2","taskStatus":1,"times":1,"maxTimes":2,"growthResult":{"addedGrowth":0}}}
做任务:天天1元购~;等待完成
{"code":"0","data":{"bizCode":"0","score":"2","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
做任务:赢锦鲤红包;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
做任务:天天领金榜年终奖;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":2,"times":1,"maxTimes":1,"growthResult":{"addedGrowth":0}}}
任务:双签领豆;已完成
任务:种豆得豆;已完成
任务:超值好货;已完成
做任务:健康新科技;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":1,"times":2,"maxTimes":4,"growthResult":{"addedGrowth":0}}}
做任务:兑权益;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"2","taskStatus":2,"times":2,"maxTimes":2,"growthResult":{"addedGrowth":0}}}
任务:天天1元购~;已完成
任务:边玩边赚;已完成
任务:逛会场;已完成
任务:双签领豆;已完成
任务:种豆得豆;已完成
任务:超值好货;已完成
做任务:领千万京喜福利;等待完成
{"code":"0","data":{"bizCode":"0"}}
{"code":"0","data":{"bizCode":"0","score":"5","taskStatus":1,"times":3,"maxTimes":4,"growthResult":{"addedGrowth":0}}}
任务:惊喜福利;已完成
任务:天天1元购~;已完成
任务:边玩边赚;已完成
任务:逛会场;已完成
任务:双签领豆;已完成
任务:种豆得豆;已完成

**Comment by klcb2010** [comment]
被拉黑了吧？我的淘金币被拉黑再折腾也只有1金币，京东这个暂时没有问题

**Comment by karma-sun** [comment]
直接登京东客户端可以领京豆，并非账户问题

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
umiIf7GX0zVp1Hq
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
YB2VUG4hmr5Pzuy
