### ISSUE TITLE
求部署文档或电报群

### ISSUE THREAD

**Issue by bonjourfan** [lukesyy/jd_yun#41]
麻烦大佬可以添加一个部署文档，或者电报群吗。看了一下，Readme里面没有文档，部署起来无从下手呀。Zero205大佬的部署方式好像跟你的有点不一样。

**Comment by lukesyy** [comment]
.github 里的文件里的内容 替换掉

**Comment by lukesyy** [comment]
青龙的话直接拉就行

**Comment by dnete** [comment]
李金岗
13884845155
15662735332
山东电子职业技术学院
1014694634@qq.com
hh2019@qq.com
https://www.weibo.com/u/5589542704
https://tieba.baidu.com/home/main?id=tb.1.af622b27._mR7-nURAhKrjW3KwC1Blw
北京通州区玉桥街道土桥中街金隅花石匠二期东区123号楼3单元101
SgCVO37y4BhTpio
山东聊城市冠县万善乡葫芦营村东南角
山东省聊城市冠县清泉街道冠县一中
山东济南市市中区七里山街道天沅大道泉景雅园商务大厦
