### ISSUE TITLE
请问如何部署时自动添加触发器内的任务？

### ISSUE THREAD

**Issue by Nicolas-Gong** [lukesyy/jd_yun#43]
尝试修改部署脚本，没搞定，直接用作者的部署脚本每次都会导致触发器内的任务丢失，得每次手动添加上去。

**Comment by lukesyy** [comment]
不要 fork  直接clone 到你的库里 然后该脚本

**Comment by Nicolas-Gong** [comment]
> 不要 fork 直接clone 到你的库里 然后该脚本


![image](https://user-images.githubusercontent.com/23067153/154447271-d019c07c-a2f1-4142-85ce-d95efc7b06ec.png)

我就是自己建库，然后clone的，不是fork过去的。改脚本是模仿上面的来写的，结果发现怎么都不行。

**Comment by lukesyy** [comment]
qq群 589445369

**Comment by dnete** [comment]
VZ5q7ETlfO8YDdi
82kkd833
