### ISSUE TITLE
Github Action部署和云函数部署是两种不同方式还是需要两边都设置配合完成部署的？

### ISSUE THREAD

**Issue by yeli008** [lukesyy/jd_yun#6]
楼主，教程看的我云里雾里，0基础，按你说的一步步布置的。能不能把教程完善下，做到小白也看得懂，谢谢。

**Comment by aligaduo689** [comment]
教程非常详细了，建仓库，自动同步，然后看云函数的就行，跟着一步一步走

**Comment by lukesyy** [comment]
已经是非常详细了

**Comment by zwb124** [comment]
说实话，我也没看懂，这教程对于没有腾讯函数和git使用基础的人简直就是天书啊，前面的还好，建仓库我看懂了，“4 部署

腾讯云函数部署【推荐】“，这里面我就真看不懂了，“在这里新建一个访问密钥新建密钥”，这里是哪里？咋新建密钥完全没写，还有腾讯云函数的创建过程也没说明，我自认还有点程序基础，可是这个教程只能给这方面的技术玩啊，各位大佬，你们这是诚心难为人啊，能不能像这个https://sitoi.gitee.io/dailycheckin/tencent-scf/的教程写一下啊？或者你们谁能教教我，我部署成功了帮你们写一版也行啊，86830348@qq.com

**Comment by zwb124** [comment]
百度了半天，又明白了一点，不懂得仓库的使用和运行机制真的有点难，不是设置难，是教程里写的东西不知道该去哪找，各位老大，真的把教程改改吧，本来其实没那么复杂，可是一看教程真的一头雾水。我还有一个疑问，腾讯平台那边，按教程写的就只是创建个函数服务就完了是吗？不需要再去里面设置或者填个代码什么的了是吗？因为我不懂整体的运行机制是什么，所以有此疑问，望有大佬回答，谢谢

**Comment by zwb124** [comment]
nb，折腾了一晚上，终于能用了，不过京东的cookie，我不是在log.gif里找到的，里面没有，不知道是不是京东更新了代码，是在另一个链接里找到的，目前暂时没问题，感谢
