### ISSUE TITLE
如何不运行JD-try？

### ISSUE THREAD

**Issue by greenwave1987** [lukesyy/jd_yun#7]
请问如何能不运行JD-try？我不用这个脚本，如何不让它运行，我自己修改，更新脚本就又被替换了。

**Comment by aligaduo689** [comment]
把云函数ac关了，自己手动开更新，每次更新自己改corn

**Comment by greenwave1987** [comment]
DREAMFACTORY_FORBID_ACCOUNT | 京喜工厂控制哪个京东账号不运行此脚本 | 非必须 | 输入1代表第一个京东账号不运行，多个使用&连接，例：1&3代表账号1和账号3不运行京喜工厂脚本，注：输入0，代表全部账号不运行京喜工厂脚本
-- | -- | -- | --
JDFACTORY_FORBID_ACCOUNT | 东东工厂控制哪个京东账号不运行此脚本 | 非必须 | 输入1代表第一个京东账号不运行，多个使用&连接，例：1&3代表账号1和账号3不运行东东工厂脚本，注：输入0，代表全部账号不运行东东工厂脚本


能不能加个这种参数，可以自己定义运行或不运行？
