### ISSUE TITLE
环境变量超过四个就提示大小超限，何解？

### ISSUE THREAD

**Issue by greenwave1987** [lukesyy/jd_yun#8]
Run node tencentscf.js
创建函数
您一共填写了5个环境变量 [
  'JD_COOKIE',
  'QYWX_AM',
  'FRUITSHARECODES',
  'DREAM_FACTORY_SHARE_CODES',
  'JD_CASH_SHARECODES'
]
Error: encentCloudSDKHttpException [Error]: 环境变量大小超限，请保持在 4KB 以内。

**Comment by greenwave1987** [comment]
cookie变量是两个帐号的，而且很长，是不是造成添加变量就超了？

**Comment by lukesyy** [comment]
简化一下cookie
